#!/bin/sh
curl -v -X POST -H "Content-Type: application/json" localhost:3000/api/issue -d "{\"name\": \"Fred Flintstone\",\"email\":\"fflintstone@gmail.com\",\"description\":\"The server was slow\"}"
