CREATE SEQUENCE IF NOT EXISTS issue_id_seq START WITH 1;

CREATE TABLE issue (
  id INTEGER NOT NULL DEFAULT NEXTVAL('issue_id_seq'),
  name VARCHAR(1000),
  email VARCHAR(1000),
  description VARCHAR(10000),
  created TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT PK_ISSUE PRIMARY KEY (id)
);

